app_deployment:
  appName: sso-oauth2-server
  image: nexus-docker-craigmiller160.ddns.net/sso-oauth2-server:latest
  configMap:
    spring.profiles.active: prod
    spring.config.location: classpath:/config/common/,classpath:/config/prod/
    spring.datasource.host: postgres.infra-prod
    spring.datasource.port: "5432"
  onepassworditems:
    - name: oauth2-server-postgres
      itemPath: vaults/Home Server (Prod)/items/Postgres Root Account
  secrets:
    - envVariable: spring.datasource.username
      secretName: oauth2-server-postgres
      secretKey: username
    - envVariable: spring.datasource.password
      secretName: oauth2-server-postgres
      secretKey: password
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8443
      scheme: HTTPS
  ports:
    - containerPort: 8443