apiVersion: v1
kind: ConfigMap
metadata:
  name: db-backup-service-configmap
data:
  db.postgres.host: postgres-service.default
  db.postgres.port: "5432"
  config.file: backup_config_prod.json
  output.root-directory: /output
  output.cleanup.age-days: "10"
  executor.interval-secs: "86400"
  email.host: https://email-service-service:8443
  email.auth.host: https://sso-oauth2-server-service.default:8443
  # TODO what are these credentials and how are they useful?
  email.auth.user: dbBackupService@gmail.com
  email.auth.password: db-backup-service-2020
  mongodump.command: /mongotools/mongodump
  db.mongo.host: mongodb-service.default
  db.mongo.port: "27017"
  logger.application.level: info
